services:
  store:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./store.sql:/docker-entrypoint-initdb.d/store.sql

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
